version: "3.8"

services:
  app:
    container_name: conect-pet-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start

  nginx:
    container_name: conect-pet-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - app
