version: "3.8"

services:
  app:
    container_name: conect-pet-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: npx ng serve --host 0.0.0.0
